import { User } from '../types/global'

export const users: User[] = [
  {
    id: 1,
    first_name: 'Maurizio',
    last_name: 'Tolomeo',
    full_name: 'Maurizio Tolomeo',
    email: 'maurizio.tolomeo@crmpartners.it',
    role: 'JUNIOR DEVELOPER',
  },
  {
    id: 2,
    first_name: 'Gabriel',
    last_name: 'Alexandru',
    full_name: 'Gabriel Alexandru',
    email: 'gabriel.alexandru@crmpartners.it',
    role: 'JUNIOR DEVELOPER',
  },
  {
    id: 3,
    first_name: 'Antonina',
    last_name: 'Napoli',
    full_name: 'Antonina Napoli',
    email: 'antonina.napoli@crmpartners.it',
    role: 'JUNIOR DEVELOPER',
  },
  {
    id: 4,
    first_name: 'Francesco',
    last_name: 'Maiali',
    full_name: 'Francesco Maiali',
    email: 'francesco.maiali@crmpartners.it',
    role: 'JUNIOR DEVELOPER',
  },
  {
    id: 5,
    first_name: 'Mattia',
    last_name: 'Piparo',
    full_name: 'Mattia Piparo',
    email: 'mattia.piparo@crmpartners.it',
    role: 'SENIOR DEVELOPER',
  },
  {
    id: 6,
    first_name: 'Giacomo Alessandro',
    last_name: 'Sardo',
    full_name: 'Giacomo Alessandro Sardo',
    email: 'giacomo.sardo@crmpartners.it',
    role: 'SENIOR DEVELOPER',
  },
  {
    id: 7,
    first_name: 'Domenico',
    last_name: 'Ruggiano',
    full_name: 'Domenico Ruggiano',
    email: 'domenico.ruggiano@crmpartners.it',
    role: 'TECHNICAL LEADER',
  },
  {
    id: 8,
    first_name: 'Simone',
    last_name: 'Mazza',
    full_name: 'Simone Mazza',
    email: 'simone.mazza@crmpartners.it',
    role: 'JUNIOR STAGE DEVELOPER',
  },
]
