name: Check Push

on: push

jobs:
  frontend:
    name: Code Quality Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      - name: Run Lint
        working-directory: ./frontend
        run: npm run lint
  backend:
    name: Code Quality Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
        working-directory: ./backend
      - name: Run Lint
        working-directory: ./backend
        run: npm run lint
  backend-build:
    name: Test Build Backend
    runs-on: ubuntu-latest
    needs: [backend]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
        working-directory: ./backend
      - name: Build Test
        working-directory: ./backend
        run: npm run build
  frontend-build:
    name: Test Build Frontend
    runs-on: ubuntu-latest
    needs: [frontend]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
      - name: Build Test
        working-directory: ./frontend
        run: npm run build