name: Check Push

on: push

jobs:
  lint_app:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ./app/node_modules
            # /home/runner/.cache/Cypress
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
      - name: Install dependencies
        run: yarn install
        working-directory: ./frontend
      - name: Run Lint
        working-directory: ./frontend
        run: yarn lint